using System.Collections.Generic;
using Eremite;
using Eremite.Buildings;

namespace ATS_API.Helpers;

public enum BuildingTypes
{
    Unknown = -1,
    None,
    Aestherics2x2_Garden,
    Aestherics2x2_GroundwaterExtractor,
    AlchemistHut,
    Altar,
    AncientGravestone,
    AncientBurrialGrounds,
    AncientGate,
    AncientShrine_T1,
    AncientTemple,
    AngryGhost1,
    AngryGhost10,
    AngryGhost14,
    AngryGhost15,
    AngryGhost16,
    AngryGhost17,
    AngryGhost18,
    AngryGhost19,
    AngryGhost2,
    AngryGhost20,
    AngryGhost21,
    AngryGhost24,
    AngryGhost31,
    AngryGhost32,
    AngryGhost34,
    AngryGhost4,
    AngryGhost5,
    AngryGhost6,
    AngryGhost9,
    AngryGhostChest_T1,
    Anvil,
    Apothecary,
    Arch,
    ArchaeologyScorpionPositive,
    ArchaeologySnakePositive,
    ArchaeologySpiderPositive,
    ArcheologyOffice,
    Artisan,
    Bakery,
    Bank,
    Barrels,
    BathHouse,
    Beanery,
    BeaverHouse,
    BeaverBattleground_T1,
    BigShelter,
    BlackStag,
    BlackTreasureStag,
    BlightPost,
    Blightrot,
    Blightrot_Clone,
    BlightrotCauldron,
    Bonfire,
    Brewery,
    BrickOven,
    Brickyard,
    Bush,
    Butcher,
    Cages,
    CalmGhost11,
    CalmGhost12,
    CalmGhost13,
    CalmGhost22,
    CalmGhost23,
    CalmGhost25,
    CalmGhost26,
    CalmGhost27,
    CalmGhost28,
    CalmGhost29,
    CalmGhost3,
    CalmGhost30,
    CalmGhost33,
    CalmGhost35,
    CalmGhost36,
    CalmGhost7,
    CalmGhost8,
    CalmGhostChest_T1,
    Camp_T1,
    Camp_T2,
    Caravan_T1,
    Caravan_T2,
    Carpenter,
    Cellar,
    Chest,
    ClanHall,
    ClayPitWorkshop,
    Clothier,
    Comfort2x2_Park,
    Cookhouse,
    Cooperage,
    CoralDecor,
    CornerFence,
    CorruptedCaravan,
    Crates,
    CrudeWorkstation,
    DebugNode_ClayBig,
    DebugNode_ClaySmall,
    DebugNode_DewberryBushBig,
    DebugNode_DewberryBushSmall,
    DebugNode_FlaxBig,
    DebugNode_FlaxSmall,
    DebugNode_HerbsBig,
    DebugNode_HerbsSmall,
    DebugNode_LeechBroodmotherBig,
    DebugNode_LeechBroodmotherSmall,
    DebugNode_Marshlands_InfiniteGrain,
    DebugNode_Marshlands_InfiniteMeat,
    DebugNode_Marshlands_InfiniteMushroom,
    DebugNode_MarshlandsMushroomBig,
    DebugNode_MarshlandsMushroomSmall,
    DebugNode_MossBroccoliBig,
    DebugNode_MossBroccoliSmall,
    DebugNode_MushroomBig,
    DebugNode_MushroomSmall,
    DebugNode_ReedBig,
    DebugNode_ReedSmall,
    DebugNode_RootsBig,
    DebugNode_RootsSmall,
    DebugNode_SeaMarrowBig,
    DebugNode_SeaMarrowSmall,
    DebugNode_SnailBroodmotherBig,
    DebugNode_SnailBroodmotherSmall,
    DebugNode_SnakeNestBig,
    DebugNode_SnakeNestSmall,
    DebugNode_StoneBig,
    DebugNode_StoneSmall,
    DebugNode_StormbirdNestBig,
    DebugNode_StormbirdNestSmall,
    DebugNode_SwampWheatBig,
    DebugNode_SwampWheatSmall,
    DebugNode_WormtongueNestBig,
    DebugNode_WormtongueNestSmall,
    DecayAltar,
    DecayAltarPositive,
    Distillery,
    Druid,
    EscapedConvicts,
    ExplorersLodge,
    Farmfield,
    Fence,
    FieldKitchen,
    Finesmith,
    FireShrine,
    FishmenCave,
    FishmenLighthouse,
    FishmenLighthousePositive,
    FishmenOutpost,
    FishmenSoothsayer,
    FishmenTotem,
    FlawlessBrewery,
    FlawlessCellar,
    FlawlessCooperage,
    FlawlessDruid,
    FlawlessLeatherworks,
    FlawlessRainMill,
    FlawlessSmelter,
    FlowerBed,
    ForagersCamp,
    ForsakenCrypt,
    Forum,
    Fountain,
    FoxFence,
    FoxFenceCorner,
    FoxHouse,
    FoxBattleground_T1,
    FumingMachinery,
    Furnace,
    Gate,
    GiantStormbird,
    GladeTrader_TheHermit,
    GladeTrader_TheSeer,
    GladeTrader_TheShaman,
    GoldStag,
    GoldTreasureStag,
    GoldenLeaf,
    Granary,
    GreenhouseWorkshop,
    Grill,
    Grove,
    GuildHouse,
    HallowedHerbGarden,
    HallowedSmallFarm,
    HarmonySpiritAltar,
    HarmonySpiritAltarPositive,
    HarpyHouse,
    HarpyBattleground_T1,
    HarvesterCamp,
    HauntedRuinedBeaverHouse,
    HauntedRuinedBrewery,
    HauntedRuinedCellar,
    HauntedRuinedCooperage,
    HauntedRuinedDruid,
    HauntedRuinedFoxHouse,
    HauntedRuinedHarpyHouse,
    HauntedRuinedHerbGarden,
    HauntedRuinedHumanHouse,
    HauntedRuinedLeatherworks,
    HauntedRuinedLizardHouse,
    HauntedRuinedMarket,
    HauntedRuinedRainmill,
    HauntedRuinedSmallFarm,
    HauntedRuinedSmelter,
    HauntedRuinedTemple,
    HerbGarden,
    HerbalistsCamp,
    HolyMarket,
    HolyTemple,
    Homestead,
    HumanHouse,
    HumanBattleground_T1,
    Hydrant,
    InfectedMole,
    InfectedTree,
    Kelpie,
    Kiln,
    Lamp,
    LeakingCauldron,
    Leatherworks,
    LightningCatcher,
    LizardHouse,
    LizardPost,
    LizardBattleground_T1,
    LoreTablet1,
    LoreTablet2,
    LoreTablet3,
    LoreTablet4,
    LoreTablet5,
    LoreTablet6,
    LoreTablet7,
    Lumbermill,
    MainStoragenot_buildable,
    MakeshiftPost,
    Manufactory,
    Market,
    MerchantShipWreck,
    Mine,
    Mistworm_T1,
    Mole,
    Monastery,
    Monolith,
    MonolithPositive,
    MushroomDecor,
    Nightfern,
    NoxiousMachinery,
    Path,
    PavedRoad,
    PetrifiedTree_T1,
    Pipe,
    PipeCross,
    PipeElbow,
    PipeEnd,
    PipeTCross,
    PipeValve,
    Plantation,
    Press,
    PrimitiveForagersCamp,
    PrimitiveHerbalistsCamp,
    PrimitiveTrappersCamp,
    Provisioner,
    PurgedBeaverHouse,
    PurgedFoxHouse,
    PurgedHarpyHouse,
    PurgedHumanHouse,
    PurgedLizardHouse,
    RainCatcher,
    RainMill,
    RainTotem,
    RainTotemPositive,
    RainpunkBarrels,
    RainpunkDrill_Coal,
    RainpunkDrill_Copper,
    RainpunkFoundry,
    RainpunkFactory,
    Ranch,
    ReinforcedRoad,
    RewardChest_T1,
    RewardChest_T2,
    RewardChest_T3,
    RoadSign,
    RuinedAdvancedRainCatcher,
    RuinedAdvancedRainCatchernoReward,
    RuinedAlchemist,
    RuinedAlchemistnoReward,
    RuinedApothecary,
    RuinedApothecarynoReward,
    RuinedArtisan,
    RuinedArtisannoReward,
    RuinedBakery,
    RuinedBakerynoReward,
    RuinedBathHouse,
    RuinedBathHousenoReward,
    RuinedBeanery,
    RuinedBeanerynoReward,
    RuinedBeaverHouse,
    RuinedBeaverHousenoReward,
    RuinedBigShelter,
    RuinedBigShelternoReward,
    RuinedBrewery,
    RuinedBrewerynoReward,
    RuinedBrickOven,
    RuinedBrickOvennoReward,
    RuinedBrickyard,
    RuinedBrickyardnoReward,
    RuinedButcher,
    RuinedButchernoReward,
    RuinedCarpenter,
    RuinedCarpenternoReward,
    RuinedCellar,
    RuinedCellarnoReward,
    RuinedClanHall,
    RuinedClanHallnoReward,
    RuinedClayPit,
    RuinedClayPitnoReward,
    RuinedCookhouse,
    RuinedCookhousenoReward,
    RuinedCooperage,
    RuinedCooperagenoReward,
    RuinedCrudeWorkstationnoReward,
    RuinedDistillery,
    RuinedDistillerynoReward,
    RuinedDruid,
    RuinedDruidnoReward,
    RuinedExplorersLodge,
    RuinedExplorersLodgenoReward,
    RuinedFarm,
    RuinedFarmnoReward,
    RuinedFieldKitchennoReward,
    RuinedFinesmith,
    RuinedFinesmithnoReward,
    RuinedForagersCamp,
    RuinedForagersCampnoReward,
    RuinedForagersCampPrimitivenoReward,
    RuinedForum,
    RuinedForumnoReward,
    RuinedFoxHouse,
    RuinedFoxHousenoReward,
    RuinedFurnace,
    RuinedFurnacenoReward,
    RuinedGranary,
    RuinedGranarynoReward,
    RuinedGreenhouse,
    RuinedGreenhousenoReward,
    RuinedGrill,
    RuinedGrillnoReward,
    RuinedGrove,
    RuinedGrovenoReward,
    RuinedGuildHouse,
    RuinedGuildHousenoReward,
    RuinedHarpyHouse,
    RuinedHarpyHousenoReward,
    RuinedHarvesterCamp,
    RuinedHarvesterCampnoReward,
    RuinedHearth,
    RuinedHearthnoReward,
    RuinedHerbGarden,
    RuinedHerbGardennoReward,
    RuinedHerbalistCamp,
    RuinedHerbalistCampnoReward,
    RuinedHerbalistCampPrimitivenoReward,
    RuinedHumanHouse,
    RuinedHumanHousenoReward,
    RuinedKiln,
    RuinedKilnnoReward,
    RuinedLeatherworks,
    RuinedLeatherworksnoReward,
    RuinedLizardHouse,
    RuinedLizardHousenoReward,
    RuinedLumbermill,
    RuinedLumbermillnoReward,
    RuinedMakeshiftPostnoReward,
    RuinedManufatory,
    RuinedManufatorynoReward,
    RuinedMarket,
    RuinedMarketnoReward,
    RuinedMinenoReward,
    RuinedMonastery,
    RuinedMonasterynoReward,
    RuinedPlantation,
    RuinedPlantationnoReward,
    RuinedPress,
    RuinedPressnoReward,
    RuinedProvisioner,
    RuinedProvisionernoReward,
    RuinedRainCatchernoReward,
    RuinedRainmill,
    RuinedRainmillnoReward,
    RuinedRanch,
    RuinedRanchnoReward,
    RuinedScribe,
    RuinedScribenoReward,
    RuinedSewer,
    RuinedSewernoReward,
    RuinedShelter,
    RuinedShelternoReward,
    RuinedSmallFarm,
    RuinedSmallFarmnoReward,
    RuinedSmelter,
    RuinedSmelternoReward,
    RuinedSmithy,
    RuinedSmithynoReward,
    RuinedSmokehouse,
    RuinedSmokehousenoReward,
    RuinedStampingMill,
    RuinedStampingMillnoReward,
    RuinedStonecutterCamp,
    RuinedStonecutterCampnoReward,
    RuinedStorage,
    RuinedStoragenoReward,
    RuinedSupplier,
    RuinedSuppliernoReward,
    RuinedTavern,
    RuinedTavernnoReward,
    RuinedTeaDoctor,
    RuinedTeaDoctornoReward,
    RuinedTeaHouse,
    RuinedTeaHousenoReward,
    RuinedTemple,
    RuinedTemplenoReward,
    RuinedTinctury,
    RuinedTincturynoReward,
    RuinedTinkerer,
    RuinedTinkerernoReward,
    RuinedToolshop,
    RuinedToolshopnoReward,
    RuinedTradingPostnoReward,
    RuinedTrappersCamp,
    RuinedTrappersCampnoReward,
    RuinedTrappersCampPrimitivenoReward,
    RuinedWeaver,
    RuinedWeavernoReward,
    RuinedWoodcuttersCamp,
    RuinedWoodcuttersCampnoReward,
    RuinedWorkshop,
    RuinedWorkshopnoReward,
    SacrificeTotem,
    SacrificeTotemPositive,
    ScarletDecor,
    Scorpion1,
    Scorpion2,
    Scorpion3,
    Scribe,
    Seal,
    SealGuidepost,
    SealLowDiff,
    SealedBiomeShrine,
    SealedTomb_T1,
    Shelter,
    Signboard,
    SmallHearth,
    SmallFarm,
    Smelter,
    Smithy,
    Smokehouse,
    Snake1,
    Snake2,
    Snake3,
    Spider1,
    Spider2,
    Spider3,
    StampingMill,
    StonecuttersCamp,
    Storagebuildable,
    StormbirdPositive,
    Supplier,
    Tavern,
    TeaDoctor,
    TeaHouse,
    Temple,
    TemporaryHearthbuildable,
    TemporaryHearthnot_buildable,
    TermiteBurrow,
    TermiteBurrowPositive,
    TIAncientShrine_T1,
    Tinctury,
    Tinkerer,
    Toolshop,
    Tower,
    TownBoard,
    TradersCemetery,
    TradingPost,
    TrappersCamp,
    Umbrella,
    Wall,
    WallCorner,
    WarBeastCage,
    WaterBarrels,
    WaterExtractor,
    Weaver,
    Well,
    WhiteStag,
    WhiteTreasureStag,
    Wildfire,
    WoodcuttersCamp,
    Workshop,
}

public static class BuildingTypesExtensions
{
    public static string ToName(this BuildingTypes type)
    {
        if (TypeToInternalName.TryGetValue(type, out var name))
        {
            return name;
        }
        
        Plugin.Log.LogError($"Cannot find name of building type: " + type);
        return BuildingTypes.Altar.ToString();
    }
    
    public static BuildingModel ToBuildingModel(this string name)
    {
        if (SO.Settings.ContainsBuilding(name))
        {
            return SO.Settings.GetBuilding(name);
        }
        
        Plugin.Log.LogError($"Cannot find name of building: " + name);
        return null;
    }

    internal static readonly Dictionary<BuildingTypes, string> TypeToInternalName = new Dictionary<BuildingTypes, string>()
    {
        { BuildingTypes.Aestherics2x2_Garden,"Aestherics 2x2 - Garden" },
        { BuildingTypes.Aestherics2x2_GroundwaterExtractor,"Aestherics 2x2 - Groundwater Extractor" },
        { BuildingTypes.AlchemistHut,"Alchemist Hut" },
        { BuildingTypes.Altar,"Altar" },
        { BuildingTypes.AncientGravestone,"Ancient Gravestone" },
        { BuildingTypes.AncientBurrialGrounds,"AncientBurrialGrounds" },
        { BuildingTypes.AncientGate,"AncientGate" },
        { BuildingTypes.AncientShrine_T1,"AncientShrine_T1" },
        { BuildingTypes.AncientTemple,"AncientTemple" },
        { BuildingTypes.AngryGhost1,"Angry Ghost 1" },
        { BuildingTypes.AngryGhost10,"Angry Ghost 10" },
        { BuildingTypes.AngryGhost14,"Angry Ghost 14" },
        { BuildingTypes.AngryGhost15,"Angry Ghost 15" },
        { BuildingTypes.AngryGhost16,"Angry Ghost 16" },
        { BuildingTypes.AngryGhost17,"Angry Ghost 17" },
        { BuildingTypes.AngryGhost18,"Angry Ghost 18" },
        { BuildingTypes.AngryGhost19,"Angry Ghost 19" },
        { BuildingTypes.AngryGhost2,"Angry Ghost 2" },
        { BuildingTypes.AngryGhost20,"Angry Ghost 20" },
        { BuildingTypes.AngryGhost21,"Angry Ghost 21" },
        { BuildingTypes.AngryGhost24,"Angry Ghost 24" },
        { BuildingTypes.AngryGhost31,"Angry Ghost 31" },
        { BuildingTypes.AngryGhost32,"Angry Ghost 32" },
        { BuildingTypes.AngryGhost34,"Angry Ghost 34" },
        { BuildingTypes.AngryGhost4,"Angry Ghost 4" },
        { BuildingTypes.AngryGhost5,"Angry Ghost 5" },
        { BuildingTypes.AngryGhost6,"Angry Ghost 6" },
        { BuildingTypes.AngryGhost9,"Angry Ghost 9" },
        { BuildingTypes.AngryGhostChest_T1,"AngryGhostChest_T1" },
        { BuildingTypes.Anvil,"Anvil" },
        { BuildingTypes.Apothecary,"Apothecary" },
        { BuildingTypes.Arch,"Arch" },
        { BuildingTypes.ArchaeologyScorpionPositive,"Archaeology Scorpion Positive" },
        { BuildingTypes.ArchaeologySnakePositive,"Archaeology Snake Positive" },
        { BuildingTypes.ArchaeologySpiderPositive,"Archaeology Spider Positive" },
        { BuildingTypes.ArcheologyOffice,"Archeology office" },
        { BuildingTypes.Artisan,"Artisan" },
        { BuildingTypes.Bakery,"Bakery" },
        { BuildingTypes.Bank,"Bank" },
        { BuildingTypes.Barrels,"Barrels" },
        { BuildingTypes.BathHouse,"Bath House" },
        { BuildingTypes.Beanery,"Beanery" },
        { BuildingTypes.BeaverHouse,"Beaver House" },
        { BuildingTypes.BeaverBattleground_T1,"BeaverBattleground_T1" },
        { BuildingTypes.BigShelter,"Big Shelter" },
        { BuildingTypes.BlackStag,"Black Stag" },
        { BuildingTypes.BlackTreasureStag,"Black Treasure Stag" },
        { BuildingTypes.BlightPost,"Blight Post" },
        { BuildingTypes.Blightrot,"Blightrot" },
        { BuildingTypes.Blightrot_Clone,"Blightrot - Clone" },
        { BuildingTypes.BlightrotCauldron,"Blightrot Cauldron" },
        { BuildingTypes.Bonfire,"Bonfire" },
        { BuildingTypes.Brewery,"Brewery" },
        { BuildingTypes.BrickOven,"Brick Oven" },
        { BuildingTypes.Brickyard,"Brickyard" },
        { BuildingTypes.Bush,"Bush" },
        { BuildingTypes.Butcher,"Butcher" },
        { BuildingTypes.Cages,"Cages" },
        { BuildingTypes.CalmGhost11,"Calm Ghost 11" },
        { BuildingTypes.CalmGhost12,"Calm Ghost 12" },
        { BuildingTypes.CalmGhost13,"Calm Ghost 13" },
        { BuildingTypes.CalmGhost22,"Calm Ghost 22" },
        { BuildingTypes.CalmGhost23,"Calm Ghost 23" },
        { BuildingTypes.CalmGhost25,"Calm Ghost 25" },
        { BuildingTypes.CalmGhost26,"Calm Ghost 26" },
        { BuildingTypes.CalmGhost27,"Calm Ghost 27" },
        { BuildingTypes.CalmGhost28,"Calm Ghost 28" },
        { BuildingTypes.CalmGhost29,"Calm Ghost 29" },
        { BuildingTypes.CalmGhost3,"Calm Ghost 3" },
        { BuildingTypes.CalmGhost30,"Calm Ghost 30" },
        { BuildingTypes.CalmGhost33,"Calm Ghost 33" },
        { BuildingTypes.CalmGhost35,"Calm Ghost 35" },
        { BuildingTypes.CalmGhost36,"Calm Ghost 36" },
        { BuildingTypes.CalmGhost7,"Calm Ghost 7" },
        { BuildingTypes.CalmGhost8,"Calm Ghost 8" },
        { BuildingTypes.CalmGhostChest_T1,"CalmGhostChest_T1" },
        { BuildingTypes.Camp_T1,"Camp_T1" },
        { BuildingTypes.Camp_T2,"Camp_T2" },
        { BuildingTypes.Caravan_T1,"Caravan_T1" },
        { BuildingTypes.Caravan_T2,"Caravan_T2" },
        { BuildingTypes.Carpenter,"Carpenter" },
        { BuildingTypes.Cellar,"Cellar" },
        { BuildingTypes.Chest,"Chest" },
        { BuildingTypes.ClanHall,"Clan Hall" },
        { BuildingTypes.ClayPitWorkshop,"Clay Pit Workshop" },
        { BuildingTypes.Clothier,"Clothier" },
        { BuildingTypes.Comfort2x2_Park,"Comfort 2x2 - Park" },
        { BuildingTypes.Cookhouse,"Cookhouse" },
        { BuildingTypes.Cooperage,"Cooperage" },
        { BuildingTypes.CoralDecor,"Coral Decor" },
        { BuildingTypes.CornerFence,"CornerFence" },
        { BuildingTypes.CorruptedCaravan,"Corrupted Caravan" },
        { BuildingTypes.Crates,"Crates" },
        { BuildingTypes.CrudeWorkstation,"Crude Workstation" },
        { BuildingTypes.DebugNode_ClayBig,"DebugNode_ClayBig" },
        { BuildingTypes.DebugNode_ClaySmall,"DebugNode_ClaySmall" },
        { BuildingTypes.DebugNode_DewberryBushBig,"DebugNode_DewberryBushBig" },
        { BuildingTypes.DebugNode_DewberryBushSmall,"DebugNode_DewberryBushSmall" },
        { BuildingTypes.DebugNode_FlaxBig,"DebugNode_FlaxBig" },
        { BuildingTypes.DebugNode_FlaxSmall,"DebugNode_FlaxSmall" },
        { BuildingTypes.DebugNode_HerbsBig,"DebugNode_HerbsBig" },
        { BuildingTypes.DebugNode_HerbsSmall,"DebugNode_HerbsSmall" },
        { BuildingTypes.DebugNode_LeechBroodmotherBig,"DebugNode_LeechBroodmotherBig" },
        { BuildingTypes.DebugNode_LeechBroodmotherSmall,"DebugNode_LeechBroodmotherSmall" },
        { BuildingTypes.DebugNode_Marshlands_InfiniteGrain,"DebugNode_Marshlands_InfiniteGrain" },
        { BuildingTypes.DebugNode_Marshlands_InfiniteMeat,"DebugNode_Marshlands_InfiniteMeat" },
        { BuildingTypes.DebugNode_Marshlands_InfiniteMushroom,"DebugNode_Marshlands_InfiniteMushroom" },
        { BuildingTypes.DebugNode_MarshlandsMushroomBig,"DebugNode_MarshlandsMushroomBig" },
        { BuildingTypes.DebugNode_MarshlandsMushroomSmall,"DebugNode_MarshlandsMushroomSmall" },
        { BuildingTypes.DebugNode_MossBroccoliBig,"DebugNode_MossBroccoliBig" },
        { BuildingTypes.DebugNode_MossBroccoliSmall,"DebugNode_MossBroccoliSmall" },
        { BuildingTypes.DebugNode_MushroomBig,"DebugNode_MushroomBig" },
        { BuildingTypes.DebugNode_MushroomSmall,"DebugNode_MushroomSmall" },
        { BuildingTypes.DebugNode_ReedBig,"DebugNode_ReedBig" },
        { BuildingTypes.DebugNode_ReedSmall,"DebugNode_ReedSmall" },
        { BuildingTypes.DebugNode_RootsBig,"DebugNode_RootsBig" },
        { BuildingTypes.DebugNode_RootsSmall,"DebugNode_RootsSmall" },
        { BuildingTypes.DebugNode_SeaMarrowBig,"DebugNode_SeaMarrowBig" },
        { BuildingTypes.DebugNode_SeaMarrowSmall,"DebugNode_SeaMarrowSmall" },
        { BuildingTypes.DebugNode_SnailBroodmotherBig,"DebugNode_SnailBroodmotherBig" },
        { BuildingTypes.DebugNode_SnailBroodmotherSmall,"DebugNode_SnailBroodmotherSmall" },
        { BuildingTypes.DebugNode_SnakeNestBig,"DebugNode_SnakeNestBig" },
        { BuildingTypes.DebugNode_SnakeNestSmall,"DebugNode_SnakeNestSmall" },
        { BuildingTypes.DebugNode_StoneBig,"DebugNode_StoneBig" },
        { BuildingTypes.DebugNode_StoneSmall,"DebugNode_StoneSmall" },
        { BuildingTypes.DebugNode_StormbirdNestBig,"DebugNode_StormbirdNestBig" },
        { BuildingTypes.DebugNode_StormbirdNestSmall,"DebugNode_StormbirdNestSmall" },
        { BuildingTypes.DebugNode_SwampWheatBig,"DebugNode_SwampWheatBig" },
        { BuildingTypes.DebugNode_SwampWheatSmall,"DebugNode_SwampWheatSmall" },
        { BuildingTypes.DebugNode_WormtongueNestBig,"DebugNode_WormtongueNestBig" },
        { BuildingTypes.DebugNode_WormtongueNestSmall,"DebugNode_WormtongueNestSmall" },
        { BuildingTypes.DecayAltar,"Decay Altar" },
        { BuildingTypes.DecayAltarPositive,"Decay Altar Positive" },
        { BuildingTypes.Distillery,"Distillery" },
        { BuildingTypes.Druid,"Druid" },
        { BuildingTypes.EscapedConvicts,"Escaped Convicts" },
        { BuildingTypes.ExplorersLodge,"Explorers Lodge" },
        { BuildingTypes.Farmfield,"Farmfield" },
        { BuildingTypes.Fence,"Fence" },
        { BuildingTypes.FieldKitchen,"Field Kitchen" },
        { BuildingTypes.Finesmith,"Finesmith" },
        { BuildingTypes.FireShrine,"Fire Shrine" },
        { BuildingTypes.FishmenCave,"Fishmen Cave" },
        { BuildingTypes.FishmenLighthouse,"Fishmen Lighthouse" },
        { BuildingTypes.FishmenLighthousePositive,"Fishmen Lighthouse Positive" },
        { BuildingTypes.FishmenOutpost,"Fishmen Outpost" },
        { BuildingTypes.FishmenSoothsayer,"Fishmen Soothsayer" },
        { BuildingTypes.FishmenTotem,"Fishmen Totem" },
        { BuildingTypes.FlawlessBrewery,"Flawless Brewery" },
        { BuildingTypes.FlawlessCellar,"Flawless Cellar" },
        { BuildingTypes.FlawlessCooperage,"Flawless Cooperage" },
        { BuildingTypes.FlawlessDruid,"Flawless Druid" },
        { BuildingTypes.FlawlessLeatherworks,"Flawless Leatherworks" },
        { BuildingTypes.FlawlessRainMill,"Flawless Rain Mill" },
        { BuildingTypes.FlawlessSmelter,"Flawless Smelter" },
        { BuildingTypes.FlowerBed,"Flower Bed" },
        { BuildingTypes.ForagersCamp,"Forager's Camp" },
        { BuildingTypes.ForsakenCrypt,"ForsakenCrypt" },
        { BuildingTypes.Forum,"Forum" },
        { BuildingTypes.Fountain,"Fountain" },
        { BuildingTypes.FoxFence,"Fox Fence" },
        { BuildingTypes.FoxFenceCorner,"Fox Fence Corner" },
        { BuildingTypes.FoxHouse,"Fox House" },
        { BuildingTypes.FoxBattleground_T1,"FoxBattleground_T1" },
        { BuildingTypes.FumingMachinery,"Fuming Machinery" },
        { BuildingTypes.Furnace,"Furnace" },
        { BuildingTypes.Gate,"Gate" },
        { BuildingTypes.GiantStormbird,"Giant Stormbird" },
        { BuildingTypes.GladeTrader_TheHermit,"Glade Trader - The Hermit" },
        { BuildingTypes.GladeTrader_TheSeer,"Glade Trader - The Seer" },
        { BuildingTypes.GladeTrader_TheShaman,"Glade Trader - The Shaman" },
        { BuildingTypes.GoldStag,"Gold Stag" },
        { BuildingTypes.GoldTreasureStag,"Gold Treasure Stag" },
        { BuildingTypes.GoldenLeaf,"Golden Leaf" },
        { BuildingTypes.Granary,"Granary" },
        { BuildingTypes.GreenhouseWorkshop,"Greenhouse Workshop" },
        { BuildingTypes.Grill,"Grill" },
        { BuildingTypes.Grove,"Grove" },
        { BuildingTypes.GuildHouse,"Guild House" },
        { BuildingTypes.HallowedHerbGarden,"Hallowed Herb Garden" },
        { BuildingTypes.HallowedSmallFarm,"Hallowed SmallFarm" },
        { BuildingTypes.HarmonySpiritAltar,"Harmony Spirit Altar" },
        { BuildingTypes.HarmonySpiritAltarPositive,"Harmony Spirit Altar Positive" },
        { BuildingTypes.HarpyHouse,"Harpy House" },
        { BuildingTypes.HarpyBattleground_T1,"HarpyBattleground_T1" },
        { BuildingTypes.HarvesterCamp,"Harvester Camp" },
        { BuildingTypes.HauntedRuinedBeaverHouse,"Haunted Ruined Beaver House" },
        { BuildingTypes.HauntedRuinedBrewery,"Haunted Ruined Brewery" },
        { BuildingTypes.HauntedRuinedCellar,"Haunted Ruined Cellar" },
        { BuildingTypes.HauntedRuinedCooperage,"Haunted Ruined Cooperage" },
        { BuildingTypes.HauntedRuinedDruid,"Haunted Ruined Druid" },
        { BuildingTypes.HauntedRuinedFoxHouse,"Haunted Ruined Fox House" },
        { BuildingTypes.HauntedRuinedHarpyHouse,"Haunted Ruined Harpy House" },
        { BuildingTypes.HauntedRuinedHerbGarden,"Haunted Ruined Herb Garden" },
        { BuildingTypes.HauntedRuinedHumanHouse,"Haunted Ruined Human House" },
        { BuildingTypes.HauntedRuinedLeatherworks,"Haunted Ruined Leatherworks" },
        { BuildingTypes.HauntedRuinedLizardHouse,"Haunted Ruined Lizard House" },
        { BuildingTypes.HauntedRuinedMarket,"Haunted Ruined Market" },
        { BuildingTypes.HauntedRuinedRainmill,"Haunted Ruined Rainmill" },
        { BuildingTypes.HauntedRuinedSmallFarm,"Haunted Ruined SmallFarm" },
        { BuildingTypes.HauntedRuinedSmelter,"Haunted Ruined Smelter" },
        { BuildingTypes.HauntedRuinedTemple,"Haunted Ruined Temple" },
        { BuildingTypes.HerbGarden,"Herb Garden" },
        { BuildingTypes.HerbalistsCamp,"Herbalist's Camp" },
        { BuildingTypes.HolyMarket,"Holy Market" },
        { BuildingTypes.HolyTemple,"Holy Temple" },
        { BuildingTypes.Homestead,"Homestead" },
        { BuildingTypes.HumanHouse,"Human House" },
        { BuildingTypes.HumanBattleground_T1,"HumanBattleground_T1" },
        { BuildingTypes.Hydrant,"Hydrant" },
        { BuildingTypes.InfectedMole,"Infected Mole" },
        { BuildingTypes.InfectedTree,"Infected Tree" },
        { BuildingTypes.Kelpie,"Kelpie" },
        { BuildingTypes.Kiln,"Kiln" },
        { BuildingTypes.Lamp,"Lamp" },
        { BuildingTypes.LeakingCauldron,"Leaking Cauldron" },
        { BuildingTypes.Leatherworks,"Leatherworks" },
        { BuildingTypes.LightningCatcher,"Lightning Catcher" },
        { BuildingTypes.LizardHouse,"Lizard House" },
        { BuildingTypes.LizardPost,"Lizard Post" },
        { BuildingTypes.LizardBattleground_T1,"LizardBattleground_T1" },
        { BuildingTypes.LoreTablet1,"Lore Tablet 1" },
        { BuildingTypes.LoreTablet2,"Lore Tablet 2" },
        { BuildingTypes.LoreTablet3,"Lore Tablet 3" },
        { BuildingTypes.LoreTablet4,"Lore Tablet 4" },
        { BuildingTypes.LoreTablet5,"Lore Tablet 5" },
        { BuildingTypes.LoreTablet6,"Lore Tablet 6" },
        { BuildingTypes.LoreTablet7,"Lore Tablet 7" },
        { BuildingTypes.Lumbermill,"Lumbermill" },
        { BuildingTypes.MainStoragenot_buildable,"Main Storage (not-buildable)" },
        { BuildingTypes.MakeshiftPost,"Makeshift Post" },
        { BuildingTypes.Manufactory,"Manufactory" },
        { BuildingTypes.Market,"Market" },
        { BuildingTypes.MerchantShipWreck,"Merchant Ship Wreck" },
        { BuildingTypes.Mine,"Mine" },
        { BuildingTypes.Mistworm_T1,"Mistworm_T1" },
        { BuildingTypes.Mole,"Mole" },
        { BuildingTypes.Monastery,"Monastery" },
        { BuildingTypes.Monolith,"Monolith" },
        { BuildingTypes.MonolithPositive,"Monolith Positive" },
        { BuildingTypes.MushroomDecor,"Mushroom Decor" },
        { BuildingTypes.Nightfern,"Nightfern" },
        { BuildingTypes.NoxiousMachinery,"Noxious Machinery" },
        { BuildingTypes.Path,"Path" },
        { BuildingTypes.PavedRoad,"Paved Road" },
        { BuildingTypes.PetrifiedTree_T1,"PetrifiedTree_T1" },
        { BuildingTypes.Pipe,"Pipe" },
        { BuildingTypes.PipeCross,"Pipe Cross" },
        { BuildingTypes.PipeElbow,"Pipe Elbow" },
        { BuildingTypes.PipeEnd,"Pipe End" },
        { BuildingTypes.PipeTCross,"Pipe T Cross" },
        { BuildingTypes.PipeValve,"Pipe Valve" },
        { BuildingTypes.Plantation,"Plantation" },
        { BuildingTypes.Press,"Press" },
        { BuildingTypes.PrimitiveForagersCamp,"Primitive Forager's Camp" },
        { BuildingTypes.PrimitiveHerbalistsCamp,"Primitive Herbalist's Camp" },
        { BuildingTypes.PrimitiveTrappersCamp,"Primitive Trapper's Camp" },
        { BuildingTypes.Provisioner,"Provisioner" },
        { BuildingTypes.PurgedBeaverHouse,"Purged Beaver House" },
        { BuildingTypes.PurgedFoxHouse,"Purged Fox House" },
        { BuildingTypes.PurgedHarpyHouse,"Purged Harpy House" },
        { BuildingTypes.PurgedHumanHouse,"Purged Human House" },
        { BuildingTypes.PurgedLizardHouse,"Purged Lizard House" },
        { BuildingTypes.RainCatcher,"Rain Catcher" },
        { BuildingTypes.RainMill,"Rain Mill" },
        { BuildingTypes.RainTotem,"Rain Totem" },
        { BuildingTypes.RainTotemPositive,"Rain Totem Positive" },
        { BuildingTypes.RainpunkBarrels,"Rainpunk Barrels" },
        { BuildingTypes.RainpunkDrill_Coal,"Rainpunk Drill - Coal" },
        { BuildingTypes.RainpunkDrill_Copper,"Rainpunk Drill - Copper" },
        { BuildingTypes.RainpunkFoundry,"Rainpunk Foundry" },
        { BuildingTypes.RainpunkFactory,"RainpunkFactory" },
        { BuildingTypes.Ranch,"Ranch" },
        { BuildingTypes.ReinforcedRoad,"Reinforced Road" },
        { BuildingTypes.RewardChest_T1,"RewardChest_T1" },
        { BuildingTypes.RewardChest_T2,"RewardChest_T2" },
        { BuildingTypes.RewardChest_T3,"RewardChest_T3" },
        { BuildingTypes.RoadSign,"Road Sign" },
        { BuildingTypes.RuinedAdvancedRainCatcher,"Ruined Advanced Rain Catcher" },
        { BuildingTypes.RuinedAdvancedRainCatchernoReward,"Ruined Advanced Rain Catcher (no reward)" },
        { BuildingTypes.RuinedAlchemist,"Ruined Alchemist" },
        { BuildingTypes.RuinedAlchemistnoReward,"Ruined Alchemist (no reward)" },
        { BuildingTypes.RuinedApothecary,"Ruined Apothecary" },
        { BuildingTypes.RuinedApothecarynoReward,"Ruined Apothecary (no reward)" },
        { BuildingTypes.RuinedArtisan,"Ruined Artisan" },
        { BuildingTypes.RuinedArtisannoReward,"Ruined Artisan (no reward)" },
        { BuildingTypes.RuinedBakery,"Ruined Bakery" },
        { BuildingTypes.RuinedBakerynoReward,"Ruined Bakery (no reward)" },
        { BuildingTypes.RuinedBathHouse,"Ruined Bath House" },
        { BuildingTypes.RuinedBathHousenoReward,"Ruined Bath House (no reward)" },
        { BuildingTypes.RuinedBeanery,"Ruined Beanery" },
        { BuildingTypes.RuinedBeanerynoReward,"Ruined Beanery (no reward)" },
        { BuildingTypes.RuinedBeaverHouse,"Ruined Beaver House" },
        { BuildingTypes.RuinedBeaverHousenoReward,"Ruined Beaver House (no reward)" },
        { BuildingTypes.RuinedBigShelter,"Ruined Big Shelter" },
        { BuildingTypes.RuinedBigShelternoReward,"Ruined Big Shelter (no reward)" },
        { BuildingTypes.RuinedBrewery,"Ruined Brewery" },
        { BuildingTypes.RuinedBrewerynoReward,"Ruined Brewery (no reward)" },
        { BuildingTypes.RuinedBrickOven,"Ruined Brick Oven" },
        { BuildingTypes.RuinedBrickOvennoReward,"Ruined Brick Oven (no reward)" },
        { BuildingTypes.RuinedBrickyard,"Ruined Brickyard" },
        { BuildingTypes.RuinedBrickyardnoReward,"Ruined Brickyard (no reward)" },
        { BuildingTypes.RuinedButcher,"Ruined Butcher" },
        { BuildingTypes.RuinedButchernoReward,"Ruined Butcher (no reward)" },
        { BuildingTypes.RuinedCarpenter,"Ruined Carpenter" },
        { BuildingTypes.RuinedCarpenternoReward,"Ruined Carpenter (no reward)" },
        { BuildingTypes.RuinedCellar,"Ruined Cellar" },
        { BuildingTypes.RuinedCellarnoReward,"Ruined Cellar (no reward)" },
        { BuildingTypes.RuinedClanHall,"Ruined Clan Hall" },
        { BuildingTypes.RuinedClanHallnoReward,"Ruined Clan Hall (no reward)" },
        { BuildingTypes.RuinedClayPit,"Ruined Clay Pit" },
        { BuildingTypes.RuinedClayPitnoReward,"Ruined Clay Pit (no reward)" },
        { BuildingTypes.RuinedCookhouse,"Ruined Cookhouse" },
        { BuildingTypes.RuinedCookhousenoReward,"Ruined Cookhouse (no reward)" },
        { BuildingTypes.RuinedCooperage,"Ruined Cooperage" },
        { BuildingTypes.RuinedCooperagenoReward,"Ruined Cooperage (no reward)" },
        { BuildingTypes.RuinedCrudeWorkstationnoReward,"Ruined Crude Workstation (no reward)" },
        { BuildingTypes.RuinedDistillery,"Ruined Distillery" },
        { BuildingTypes.RuinedDistillerynoReward,"Ruined Distillery (no reward)" },
        { BuildingTypes.RuinedDruid,"Ruined Druid" },
        { BuildingTypes.RuinedDruidnoReward,"Ruined Druid (no reward)" },
        { BuildingTypes.RuinedExplorersLodge,"Ruined Explorers Lodge" },
        { BuildingTypes.RuinedExplorersLodgenoReward,"Ruined Explorers Lodge (no reward)" },
        { BuildingTypes.RuinedFarm,"Ruined Farm" },
        { BuildingTypes.RuinedFarmnoReward,"Ruined Farm (no reward)" },
        { BuildingTypes.RuinedFieldKitchennoReward,"Ruined Field Kitchen (no reward)" },
        { BuildingTypes.RuinedFinesmith,"Ruined Finesmith" },
        { BuildingTypes.RuinedFinesmithnoReward,"Ruined Finesmith (no reward)" },
        { BuildingTypes.RuinedForagersCamp,"Ruined Foragers Camp" },
        { BuildingTypes.RuinedForagersCampnoReward,"Ruined Foragers Camp (no reward)" },
        { BuildingTypes.RuinedForagersCampPrimitivenoReward,"Ruined Foragers Camp Primitive (no reward)" },
        { BuildingTypes.RuinedForum,"Ruined Forum" },
        { BuildingTypes.RuinedForumnoReward,"Ruined Forum (no reward)" },
        { BuildingTypes.RuinedFoxHouse,"Ruined Fox House" },
        { BuildingTypes.RuinedFoxHousenoReward,"Ruined Fox House (no reward)" },
        { BuildingTypes.RuinedFurnace,"Ruined Furnace" },
        { BuildingTypes.RuinedFurnacenoReward,"Ruined Furnace (no reward)" },
        { BuildingTypes.RuinedGranary,"Ruined Granary" },
        { BuildingTypes.RuinedGranarynoReward,"Ruined Granary (no reward)" },
        { BuildingTypes.RuinedGreenhouse,"Ruined Greenhouse" },
        { BuildingTypes.RuinedGreenhousenoReward,"Ruined Greenhouse (no reward)" },
        { BuildingTypes.RuinedGrill,"Ruined Grill" },
        { BuildingTypes.RuinedGrillnoReward,"Ruined Grill (no reward)" },
        { BuildingTypes.RuinedGrove,"Ruined Grove" },
        { BuildingTypes.RuinedGrovenoReward,"Ruined Grove (no reward)" },
        { BuildingTypes.RuinedGuildHouse,"Ruined Guild House" },
        { BuildingTypes.RuinedGuildHousenoReward,"Ruined Guild House (no reward)" },
        { BuildingTypes.RuinedHarpyHouse,"Ruined Harpy House" },
        { BuildingTypes.RuinedHarpyHousenoReward,"Ruined Harpy House (no reward)" },
        { BuildingTypes.RuinedHarvesterCamp,"Ruined Harvester Camp" },
        { BuildingTypes.RuinedHarvesterCampnoReward,"Ruined Harvester Camp (no reward)" },
        { BuildingTypes.RuinedHearth,"Ruined Hearth" },
        { BuildingTypes.RuinedHearthnoReward,"Ruined Hearth (no reward)" },
        { BuildingTypes.RuinedHerbGarden,"Ruined Herb Garden" },
        { BuildingTypes.RuinedHerbGardennoReward,"Ruined Herb Garden (no reward)" },
        { BuildingTypes.RuinedHerbalistCamp,"Ruined Herbalist Camp" },
        { BuildingTypes.RuinedHerbalistCampnoReward,"Ruined Herbalist Camp (no reward)" },
        { BuildingTypes.RuinedHerbalistCampPrimitivenoReward,"Ruined Herbalist Camp primitive (no reward)" },
        { BuildingTypes.RuinedHumanHouse,"Ruined Human House" },
        { BuildingTypes.RuinedHumanHousenoReward,"Ruined Human House (no reward)" },
        { BuildingTypes.RuinedKiln,"Ruined Kiln" },
        { BuildingTypes.RuinedKilnnoReward,"Ruined Kiln (no reward)" },
        { BuildingTypes.RuinedLeatherworks,"Ruined Leatherworks" },
        { BuildingTypes.RuinedLeatherworksnoReward,"Ruined Leatherworks (no reward)" },
        { BuildingTypes.RuinedLizardHouse,"Ruined Lizard House" },
        { BuildingTypes.RuinedLizardHousenoReward,"Ruined Lizard House (no reward)" },
        { BuildingTypes.RuinedLumbermill,"Ruined Lumbermill" },
        { BuildingTypes.RuinedLumbermillnoReward,"Ruined Lumbermill (no reward)" },
        { BuildingTypes.RuinedMakeshiftPostnoReward,"Ruined Makeshift Post (no reward)" },
        { BuildingTypes.RuinedManufatory,"Ruined Manufatory" },
        { BuildingTypes.RuinedManufatorynoReward,"Ruined Manufatory (no reward)" },
        { BuildingTypes.RuinedMarket,"Ruined Market" },
        { BuildingTypes.RuinedMarketnoReward,"Ruined Market (no reward)" },
        { BuildingTypes.RuinedMinenoReward,"Ruined Mine (no reward)" },
        { BuildingTypes.RuinedMonastery,"Ruined Monastery" },
        { BuildingTypes.RuinedMonasterynoReward,"Ruined Monastery (no reward)" },
        { BuildingTypes.RuinedPlantation,"Ruined Plantation" },
        { BuildingTypes.RuinedPlantationnoReward,"Ruined Plantation (no reward)" },
        { BuildingTypes.RuinedPress,"Ruined Press" },
        { BuildingTypes.RuinedPressnoReward,"Ruined Press (no reward)" },
        { BuildingTypes.RuinedProvisioner,"Ruined Provisioner" },
        { BuildingTypes.RuinedProvisionernoReward,"Ruined Provisioner (no reward)" },
        { BuildingTypes.RuinedRainCatchernoReward,"Ruined Rain Catcher (no reward)" },
        { BuildingTypes.RuinedRainmill,"Ruined Rainmill" },
        { BuildingTypes.RuinedRainmillnoReward,"Ruined Rainmill (no reward)" },
        { BuildingTypes.RuinedRanch,"Ruined Ranch" },
        { BuildingTypes.RuinedRanchnoReward,"Ruined Ranch (no reward)" },
        { BuildingTypes.RuinedScribe,"Ruined Scribe" },
        { BuildingTypes.RuinedScribenoReward,"Ruined Scribe (no reward)" },
        { BuildingTypes.RuinedSewer,"Ruined Sewer" },
        { BuildingTypes.RuinedSewernoReward,"Ruined Sewer (no reward)" },
        { BuildingTypes.RuinedShelter,"Ruined Shelter" },
        { BuildingTypes.RuinedShelternoReward,"Ruined Shelter (no reward)" },
        { BuildingTypes.RuinedSmallFarm,"Ruined SmallFarm" },
        { BuildingTypes.RuinedSmallFarmnoReward,"Ruined SmallFarm (no reward)" },
        { BuildingTypes.RuinedSmelter,"Ruined Smelter" },
        { BuildingTypes.RuinedSmelternoReward,"Ruined Smelter (no reward)" },
        { BuildingTypes.RuinedSmithy,"Ruined Smithy" },
        { BuildingTypes.RuinedSmithynoReward,"Ruined Smithy (no reward)" },
        { BuildingTypes.RuinedSmokehouse,"Ruined Smokehouse" },
        { BuildingTypes.RuinedSmokehousenoReward,"Ruined Smokehouse (no reward)" },
        { BuildingTypes.RuinedStampingMill,"Ruined Stamping Mill" },
        { BuildingTypes.RuinedStampingMillnoReward,"Ruined Stamping Mill (no reward)" },
        { BuildingTypes.RuinedStonecutterCamp,"Ruined Stonecutter Camp" },
        { BuildingTypes.RuinedStonecutterCampnoReward,"Ruined Stonecutter Camp (no reward)" },
        { BuildingTypes.RuinedStorage,"Ruined Storage" },
        { BuildingTypes.RuinedStoragenoReward,"Ruined Storage (no reward)" },
        { BuildingTypes.RuinedSupplier,"Ruined Supplier" },
        { BuildingTypes.RuinedSuppliernoReward,"Ruined Supplier (no reward)" },
        { BuildingTypes.RuinedTavern,"Ruined Tavern" },
        { BuildingTypes.RuinedTavernnoReward,"Ruined Tavern (no reward)" },
        { BuildingTypes.RuinedTeaDoctor,"Ruined Tea Doctor" },
        { BuildingTypes.RuinedTeaDoctornoReward,"Ruined Tea Doctor (no reward)" },
        { BuildingTypes.RuinedTeaHouse,"Ruined Tea House" },
        { BuildingTypes.RuinedTeaHousenoReward,"Ruined Tea House (no reward)" },
        { BuildingTypes.RuinedTemple,"Ruined Temple" },
        { BuildingTypes.RuinedTemplenoReward,"Ruined Temple (no reward)" },
        { BuildingTypes.RuinedTinctury,"Ruined Tinctury" },
        { BuildingTypes.RuinedTincturynoReward,"Ruined Tinctury (no reward)" },
        { BuildingTypes.RuinedTinkerer,"Ruined Tinkerer" },
        { BuildingTypes.RuinedTinkerernoReward,"Ruined Tinkerer (no reward)" },
        { BuildingTypes.RuinedToolshop,"Ruined Toolshop" },
        { BuildingTypes.RuinedToolshopnoReward,"Ruined Toolshop (no reward)" },
        { BuildingTypes.RuinedTradingPostnoReward,"Ruined Trading Post (no reward)" },
        { BuildingTypes.RuinedTrappersCamp,"Ruined Trappers Camp" },
        { BuildingTypes.RuinedTrappersCampnoReward,"Ruined Trappers Camp (no reward)" },
        { BuildingTypes.RuinedTrappersCampPrimitivenoReward,"Ruined Trappers Camp Primitive (no reward)" },
        { BuildingTypes.RuinedWeaver,"Ruined Weaver" },
        { BuildingTypes.RuinedWeavernoReward,"Ruined Weaver (no reward)" },
        { BuildingTypes.RuinedWoodcuttersCamp,"Ruined Woodcutters Camp" },
        { BuildingTypes.RuinedWoodcuttersCampnoReward,"Ruined Woodcutters Camp (no reward)" },
        { BuildingTypes.RuinedWorkshop,"Ruined Workshop" },
        { BuildingTypes.RuinedWorkshopnoReward,"Ruined Workshop (no reward)" },
        { BuildingTypes.SacrificeTotem,"Sacrifice Totem" },
        { BuildingTypes.SacrificeTotemPositive,"Sacrifice Totem Positive" },
        { BuildingTypes.ScarletDecor,"Scarlet Decor" },
        { BuildingTypes.Scorpion1,"Scorpion 1" },
        { BuildingTypes.Scorpion2,"Scorpion 2" },
        { BuildingTypes.Scorpion3,"Scorpion 3" },
        { BuildingTypes.Scribe,"Scribe" },
        { BuildingTypes.Seal,"Seal" },
        { BuildingTypes.SealGuidepost,"Seal Guidepost" },
        { BuildingTypes.SealLowDiff,"Seal Low Diff" },
        { BuildingTypes.SealedBiomeShrine,"Sealed Biome Shrine" },
        { BuildingTypes.SealedTomb_T1,"SealedTomb_T1" },
        { BuildingTypes.Shelter,"Shelter" },
        { BuildingTypes.Signboard,"Signboard" },
        { BuildingTypes.SmallHearth,"Small Hearth" },
        { BuildingTypes.SmallFarm,"SmallFarm" },
        { BuildingTypes.Smelter,"Smelter" },
        { BuildingTypes.Smithy,"Smithy" },
        { BuildingTypes.Smokehouse,"Smokehouse" },
        { BuildingTypes.Snake1,"Snake 1" },
        { BuildingTypes.Snake2,"Snake 2" },
        { BuildingTypes.Snake3,"Snake 3" },
        { BuildingTypes.Spider1,"Spider 1" },
        { BuildingTypes.Spider2,"Spider 2" },
        { BuildingTypes.Spider3,"Spider 3" },
        { BuildingTypes.StampingMill,"Stamping Mill" },
        { BuildingTypes.StonecuttersCamp,"Stonecutter's Camp" },
        { BuildingTypes.Storagebuildable,"Storage (buildable)" },
        { BuildingTypes.StormbirdPositive,"Stormbird Positive" },
        { BuildingTypes.Supplier,"Supplier" },
        { BuildingTypes.Tavern,"Tavern" },
        { BuildingTypes.TeaDoctor,"Tea Doctor" },
        { BuildingTypes.TeaHouse,"Tea House" },
        { BuildingTypes.Temple,"Temple" },
        { BuildingTypes.TemporaryHearthbuildable,"Temporary Hearth (buildable)" },
        { BuildingTypes.TemporaryHearthnot_buildable,"Temporary Hearth (not-buildable)" },
        { BuildingTypes.TermiteBurrow,"Termite Burrow" },
        { BuildingTypes.TermiteBurrowPositive,"Termite Burrow Positive" },
        { BuildingTypes.TIAncientShrine_T1,"TI AncientShrine_T1" },
        { BuildingTypes.Tinctury,"Tinctury" },
        { BuildingTypes.Tinkerer,"Tinkerer" },
        { BuildingTypes.Toolshop,"Toolshop" },
        { BuildingTypes.Tower,"Tower" },
        { BuildingTypes.TownBoard,"Town Board" },
        { BuildingTypes.TradersCemetery,"Traders Cemetery" },
        { BuildingTypes.TradingPost,"Trading Post" },
        { BuildingTypes.TrappersCamp,"Trapper's Camp" },
        { BuildingTypes.Umbrella,"Umbrella" },
        { BuildingTypes.Wall,"Wall" },
        { BuildingTypes.WallCorner,"Wall Corner" },
        { BuildingTypes.WarBeastCage,"War Beast Cage" },
        { BuildingTypes.WaterBarrels,"Water Barrels" },
        { BuildingTypes.WaterExtractor,"Water Extractor" },
        { BuildingTypes.Weaver,"Weaver" },
        { BuildingTypes.Well,"Well" },
        { BuildingTypes.WhiteStag,"White Stag" },
        { BuildingTypes.WhiteTreasureStag,"White Treasure Stag" },
        { BuildingTypes.Wildfire,"Wildfire" },
        { BuildingTypes.WoodcuttersCamp,"Woodcutters Camp" },
        { BuildingTypes.Workshop,"Workshop" },
    };
}